import type { NextPage } from 'next';
import Head from 'next/head';
import { useCallback, useMemo, useState } from "react";

import Card from "@verse/components/Card";

import Squares from "assets/tokens/Squares";

const TEMP_ADDRESS = "0xfC4b619a481E139CfC4fC54E0E7218F8c393bDE5";

const Home: NextPage = () => {

  const [walletAddress, setWalletAddress] = useState(TEMP_ADDRESS);

  const shortenAddress = useMemo(() => {
    const length = walletAddress.length;
    return `${walletAddress.slice(0, 7)}...${walletAddress.slice(length - 5)}`
  }, [walletAddress]);

  const handleCopyAddress = useCallback(() => {
    window.navigator.clipboard.writeText(walletAddress);
  }, [walletAddress]);

  return (
    <div>
      <Head>
        <title>Verse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <div className="flex justify-between mt-10">
          <div>
            <button>add</button>
          </div>
          <div>
            <div className="flex gap-x-2">
              <h5 className="text-right">{shortenAddress}</h5>
              <button onClick={handleCopyAddress}>
                <Squares/>
              </button>
            </div>
          </div>
        </div>
        <hr className="my-2 mb-6"/>
      </nav>
      <main className="max-w-max mx-auto">
        <div className="flex flex-col gap-y-2">
          <Card
            userId="1"
            username="bobthebuilder"
            location="san diego"
            photo="https://images.unsplash.com/photo-1658194930798-2c52f9d49c20?fit=crop&w=2370&q=80"
          />
          <Card
            userId="1"
            location="los angeles"
            photo="https://images.unsplash.com/photo-1658236252852-259aa718f3be?auto=format&fit=crop&w=987&q=80"
          />
          <Card
            userId="1"
            location="north korea"
            photo="https://images.unsplash.com/photo-1599536837271-f3e08bd0fac5?auto=format&fit=crop&w=987&q=80"
          />
        </div>
      </main>
      <footer className="m-5">
        <hr className="mb-2"/>
        <span className="text-sm">© 2022 Verse</span>
      </footer>
    </div>
  );
}

export default Home;
